title: [SisMOM AI Team portfolio]
description: [part of SisMOM / INPE / MCTI project]

# architect | cayman | dinky | hacker | leap-day | merlot | midnight | minima | minimal | modernist | slate | tactile | time-machine
remote_theme: pages-themes/modeernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

google_analytics: [G-MBNLDSJ3CC]

# My variables
ship_paper: https://www.researchgate.net/publication/270769959_Hierarchical_ship_detection_and_recognition_with_high-resolution_polarimetric_synthetic_aperture_radar_imagery
